RUN_PERIOD_SECONDS = 10
CHECK_FOR_DB_SECONDS = 5
BUF_SIZE = 65536
YAML_FILE_NAME = 'permissions.yaml'
MYSQL_HOST = "db"
MYSQL_USER = "root"
MYSQL_ROOT_PASSWORD = "notSecureChangeMe"
MYSQL_DEFAULT_DATABASE = "mysql"