version: "3.7"
services:

  db:
    image: mariadb:10.6
    restart: always
    env_file:
      - .env
    ports:
      - 3306:3306
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
  
  update-permissions:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: update-permissions-app
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db
