version: "3.7"
services:

  db:
    image: mariadb:10.6
    restart: always
    ports:
      - 3306
    env_file:
      - .env
  
  update-permissions:
    image: miladbeigi/sample-project:0.2.0
    env_file:
      - .env
    volumes:
      - mylogs:/app/logs
    depends_on:
      - db

volumes:
  mylogs:
