version: "3.7"
services:

  db:
    image: mariadb:10.6
    restart: always
    ports:
      - 3306
    env_file:
      - .env
  
  update-permissions:
    image: miladbeigi/sample-project:0.1.1
    env_file:
      - .env
    volumes:
      - /app/update-permissions.log
    depends_on:
      - db
