version: "3.7"
services:

  db:
    image: mariadb:10.6
    restart: always
    env_file:
      - .env
    ports:
      - 3306:3306

  update-permissions:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: update-permissions-app
    env_file:
      - .env
    volumes:
      - .:/app/
    depends_on:
      - db
