apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.prod.yaml
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: update-permissions
  name: update-permissions
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: update-permissions
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.prod.yaml
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: update-permissions
    spec:
      containers:
        - env:
            - name: MYSQL_DEFAULT_DATABASE
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_DEFAULT_DATABASE
                  name: env
            - name: MYSQL_HOST
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_HOST
                  name: env
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_ROOT_PASSWORD
                  name: env
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_USER
                  name: env
          image: miladbeigi/sample-project:0.1.2
          name: update-permissions
          resources: {}
          volumeMounts:
            - mountPath: /app/logs
              name: mylogs
      restartPolicy: Always
      volumes:
        - name: mylogs
          persistentVolumeClaim:
            claimName: mylogs
status: {}
